name: Golang Sample Deploy

on:
  release:
    types: [published]

jobs:

  docker-build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to GCR
      uses: docker/login-action@v2
      with:
        registry: asia.gcr.io
        username: _json_key
        password: ${{ secrets.GCR }}
        
    - name: Build and push to docker hub
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: asia.gcr.io/studidevops-369306/goapp:${{ github.ref_name }}

  binary-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - run: mkdir build

    - name: Build Linux AMD64
      run: GOOS=linux GOARCH=amd64 go build -o build/linux-amd64 .

    - name: Build Windows AMD64
      run: GOOS=windows GOARCH=amd64 go build -o build/windows-amd64.exe .

    - name: Build Darwin AMD64
      run: GOOS=darwin GOARCH=amd64 go build -o build/darwin-amd64 .

    - name: Build Darwin ARM64
      run: GOOS=darwin GOARCH=arm64 go build -o build/darwin-arm64 .
    
    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: build/*
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
