name: Binary Release CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build Linux AMD64
      run: GOOS=linux GOARCH=amd64 go build -o linux-amd64 .

    - name: Build Windows AMD64
      run: GOOS=windows GOARCH=amd64 go build -o windows-amd64.exe .

    - name: Build Darwin AMD64
      run: GOOS=darwin GOARCH=amd64 go build -o darwin-amd64 .

    - name: Build Darwin ARM64
      run: GOOS=darwin GOARCH=arm64 go build -o darwin-arm64 .